port: 7890
socks-port: 7891
mixed-port: 7892
allow-lan: true
bind-address: "0.0.0.0"
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
secret: test123

dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
    - 8.8.8.8

proxies:
  - name: "direct"
    type: direct

proxy-groups:
  - name: "auto"
    type: select
    proxies:
      - direct

rules:
  - MATCH,auto